require_all 'app/'

User.create(name: "Parik")
User.create(name: "Chris")
User.create(name: "Shane")
User.create(name: "Sapphie")
User.create(name: "Minha")
User.create(name: "Joey")
User.create(name: "Matt")
User.create(name: "Jake")
User.create(name: "Song")
User.create(name: "Yannick")
User.create(name: "Sam")
User.create(name: "Terry")
User.create(name: "Cristi")
User.create(name: "Joel")
User.create(name: "Deeva")
User.create(name: "Cristina")
User.create(name: "Justine")
User.create(name: "Lizzy")
User.create(name: "Maya")
User.create(name: "Naweed")
User.create(name: "Dan")


Country.create(name: "England")
Country.create(name: "France")
Country.create(name: "Spain")
Country.create(name: "Portugal")
Country.create(name: "Germany")
Country.create(name: "Poland")
Country.create(name: "Russia")
Country.create(name: "Brazil")
Country.create(name: "Italy")
Country.create(name: "Belgium")
Country.create(name: "Netherlands")
Country.create(name: "Denmark")
Country.create(name: "Greece")
Country.create(name: "Sweden")
Country.create(name: "Hungary")
Country.create(name: "Turkey")
Country.create(name: "USA")
Country.create(name: "China")
Country.create(name: "Japan")
Country.create(name: "India")
Country.create(name: "World")

# Turkish Super Lig
League.create(api_league_id: 112, country_id: 16)
# Jupiler Pro
League.create(api_league_id: 171, country_id: 10)
# Swedish League
League.create(api_league_id: 18, country_id: 14)
# Bundesliga
League.create(api_league_id: 8, country_id: 5)


Team.create(api_team_id: 44)
Team.create(api_team_id: 35)
Team.create(api_team_id: 52)
Team.create(api_team_id: 60)
Team.create(api_team_id: 37)
Team.create(api_team_id: 42)
Team.create(api_team_id: 40)
Team.create(api_team_id: 51)
Team.create(api_team_id: 33)
Team.create(api_team_id: 38)
Team.create(api_team_id: 34)
Team.create(api_team_id: 49)
Team.create(api_team_id: 41)
Team.create(api_team_id: 50)
Team.create(api_team_id: 76)
Team.create(api_team_id: 75)
Team.create(api_team_id: 47)
Team.create(api_team_id: 46)
Team.create(api_team_id: 48)
Team.create(api_team_id: 45)

Team.create(api_team_id: 733)
Team.create(api_team_id: 631)
Team.create(api_team_id: 734)
Team.create(api_team_id: 736)

Team.create(api_team_id: 98)
Team.create(api_team_id: 110)
Team.create(api_team_id: 99)
Team.create(api_team_id: 107)


Team.create(api_team_id: 100)
Team.create(api_team_id: 114)
Team.create(api_team_id: 101)
Team.create(api_team_id: 102)


Team.create(api_team_id: 113)
Team.create(api_team_id: 105)
Team.create(api_team_id: 111)
Team.create(api_team_id: 112)
